### ISSUE TITLE
Repo link template seems to be off?

### ISSUE THREAD

**Issue by InaSLew** [marczaku/104-csharp-oop#1]
Hi Marc 👋 Just noticed that the repo link in [003.4-console-methods](https://github.com/marczaku/csharp-oop/blob/main/assignments/003.4-console-methods.md) still says
`gp21-21-0927-csharp-basics-nim-[yourusername]`
instead of the one we start on this week ⬇⬇⬇
`gp21-21-1004-csharp-oop-rpg-[yourusername]`

Just wondering if it's supposed to be like that? 🤔

**Comment by marczaku** [comment]
Fixed, but forgot to close the issue. Thanks! :)
